/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    EventCard: typeof import('./src/components/events/EventCard.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroBanner: typeof import('./src/components/hero/HeroBanner.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    Menu: typeof import('primevue/menu')['default']
    NavBar: typeof import('./src/components/navbar/NavBar.vue')['default']
    NavbarActions: typeof import('./src/components/navbar/NavbarActions.vue')['default']
    NavbarLogo: typeof import('./src/components/navbar/NavbarLogo.vue')['default']
    NavbarSearch: typeof import('./src/components/navbar/NavbarSearch.vue')['default']
    NavbarUserActions: typeof import('./src/components/navbar/NavbarUserActions.vue')['default']
    PopularEvents: typeof import('./src/components/events/PopularEvents.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitButton: typeof import('primevue/splitbutton')['default']
    TheFooter: typeof import('./src/components/footer/TheFooter.vue')['default']
    TheMap: typeof import('./src/components/map/TheMap.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
