/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllEvents: typeof import('./src/components/admin/AllEvents.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Carousel: typeof import('primevue/carousel')['default']
    ContinueWith: typeof import('./src/components/login/ContinueWith.vue')['default']
    copy: typeof import('./src/components/login/LoginForm copy.vue')['default']
    EventCard: typeof import('./src/components/events/EventCard.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroBanner: typeof import('./src/components/hero/HeroBanner.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginForm: typeof import('./src/components/login/LoginForm.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    NavBar: typeof import('./src/components/navbar/NavBar.vue')['default']
    NavbarActions: typeof import('./src/components/navbar/NavbarActions.vue')['default']
    NavbarLogo: typeof import('./src/components/navbar/NavbarLogo.vue')['default']
    NavbarSearch: typeof import('./src/components/navbar/NavbarSearch.vue')['default']
    NavbarUserActions: typeof import('./src/components/navbar/NavbarUserActions.vue')['default']
    Password: typeof import('primevue/password')['default']
    PopularEvents: typeof import('./src/components/events/PopularEvents.vue')['default']
    RegisterForm: typeof import('./src/components/login/RegisterForm.vue')['default']
    RejectedEvents: typeof import('./src/components/admin/RejectedEvents.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitButton: typeof import('primevue/splitbutton')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    Tag: typeof import('primevue/tag')['default']
    TheFooter: typeof import('./src/components/footer/TheFooter.vue')['default']
    TheMap: typeof import('./src/components/map/TheMap.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    ValidateEvents: typeof import('./src/components/admin/ValidateEvents.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
