name: Deploy to VM

on:
  push:
    branches:
      - main
  pull_request:
    types: [labeled]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 89.168.46.10 >> ~/.ssh/known_hosts

    - name: Set deploy path based on label
      id: set-deploy-path
      run: |
        if [[ "${{ github.event.pull_request.labels }}" == *"sandbox"* ]]; then
          echo "deploy_path=MMAESGI/sandbox/Rasso_Frontend" >> $GITHUB_ENV
        else
          echo "deploy_path=MMAESGI/production/Rasso_Frontend" >> $GITHUB_ENV
        fi

    - name: Deploy over SSH
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@89.168.46.10 << 'EOF'
          cd ${{ env.deploy_path }}
          git pull origin main
          docker compose down
          docker compose up -d
        EOF
