name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 89.168.46.10 >> ~/.ssh/known_hosts

    - name: Deploy on Production VM
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@89.168.46.10 << 'EOF'
          set -e
          cd MMAESGI/production/Rasso_Frontend

          git fetch --alls
          git reset --hard origin/main

          npm install

          echo "Deploying latest production code"
          cd ..
          docker compose -f docker-compose-front.yml down
          docker compose -f docker-compose-front.yml up -d
        EOF
